#!/usr/bin/env python3
"""
Apex Rover Raspberry Voice + Auto Camera Scan Service - CLEAN VERSION

Responsibilities:
  1) Listen to ESP32 command mirrors on UDP port 5055.
  2) Speak robot commands using espeak-ng.
  3) Play idle music when no command is arriving.
  4) Apply ONLY system mode commands on Raspberry:
       SYS:MODE:AUTO
         - speak it,
         - notify main_startup.py to switch Raspberry camera service to AUTO,
         - start organized camera stand scan,
         - send AUTO:FULL_SCENARIO to ESP32.
       SYS:MODE:MANUAL
         - speak it,
         - stop organized camera stand scan,
         - notify main_startup.py to switch Raspberry camera service to MANUAL.

Normal commands are voice-only on Raspberry.
Raspberry does NOT read Mega USB Serial anymore.

Music:
  Put your music file beside this script.
  Default name: idle_music.mp3

Install:
  sudo apt update
  sudo apt install -y espeak-ng mpg123 ffmpeg

Run manually:
  python3 raspberry_voice_auto_service.py

main_startup.py should start this file automatically.
"""

from __future__ import annotations

import json
import os
import signal
import socket
import subprocess
import threading
import time
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


# ============================================================
# Configuration
# ============================================================

ESP32_IP = os.environ.get("APEX_ESP32_IP", "192.168.4.1")
ESP32_HTTP_PORT = int(os.environ.get("APEX_ESP32_HTTP_PORT", "80"))

UDP_LISTEN_IP = "0.0.0.0"
UDP_LISTEN_PORT = int(os.environ.get("APEX_RPI_UDP_PORT", "5055"))

BASE_DIR = Path(__file__).resolve().parent
IDLE_MUSIC_FILE = BASE_DIR / os.environ.get("APEX_IDLE_MUSIC", "idle_music.mp3")
IDLE_MUSIC_DELAY_SEC = float(os.environ.get("APEX_IDLE_MUSIC_DELAY", "4.0"))

# main_startup.py local endpoint. It starts/stops camera services.
RPI_MODE_URL = os.environ.get("APEX_RPI_MODE_URL", "http://127.0.0.1:5050/internal/mode_from_voice")

TTS_BINARIES = ["espeak-ng", "espeak"]
TTS_VOICE = os.environ.get("APEX_TTS_VOICE", "en-us")
TTS_SPEED = os.environ.get("APEX_TTS_SPEED", "150")

# Auto camera scan pattern.
# Servo angles must stay inside 0..90.
AUTO_SCAN_ENABLED = True
AUTO_SCAN_SERVO_ANGLES = [0, 45, 90]
AUTO_SCAN_STEP_LEFT = 100
AUTO_SCAN_STEP_RIGHT = 150
AUTO_SCAN_RETURN_LEFT = 50
AUTO_SCAN_DELAY_SEC = 0.75
AUTO_SCAN_CYCLE_PAUSE_SEC = 0.35

SEND_FULL_SCENARIO_ON_AUTO = True
FULL_SCENARIO_DELAY_SEC = 0.8

# Same command may arrive twice because ESP32 mirrors IN and OUT.
DUPLICATE_COMMAND_WINDOW_SEC = 1.2
SYSTEM_MODE_DUPLICATE_WINDOW_SEC = 4.0

# Commands generated by this Raspberry service should not be spoken again
# when ESP32 mirrors them back.
SELF_SENT_IGNORE_WINDOW_SEC = 3.0

_stop_event = threading.Event()
_print_lock = threading.Lock()


def log(message: str) -> None:
    with _print_lock:
        print(message, flush=True)


def find_binary(names: list[str]) -> Optional[str]:
    for name in names:
        try:
            result = subprocess.run(
                ["which", name],
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                text=True,
                check=False,
            )
            path = result.stdout.strip()
            if path:
                return path
        except Exception:
            pass
    return None


# ============================================================
# Self-sent command silence tracker
# ============================================================

class SelfSentSilencer:
    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._items: dict[str, float] = {}

    def add(self, command: str) -> None:
        command = command.strip().upper()
        if not command:
            return
        with self._lock:
            self._items[command] = time.time()

    def should_ignore(self, command: str) -> bool:
        command = command.strip().upper()
        now = time.time()
        with self._lock:
            expired = [cmd for cmd, ts in self._items.items() if now - ts > SELF_SENT_IGNORE_WINDOW_SEC]
            for cmd in expired:
                self._items.pop(cmd, None)

            ts = self._items.get(command)
            if ts is None:
                return False
            if now - ts <= SELF_SENT_IGNORE_WINDOW_SEC:
                return True
            self._items.pop(command, None)
            return False


self_sent = SelfSentSilencer()


# ============================================================
# ESP32 / local mode command helpers
# ============================================================

def esp32_command_url(command: str) -> str:
    encoded = urllib.parse.quote(command, safe="")
    return f"http://{ESP32_IP}:{ESP32_HTTP_PORT}/command?cmd={encoded}"


def send_command_to_esp32(command: str, timeout: float = 1.5, silent_when_mirrored: bool = True) -> bool:
    if silent_when_mirrored:
        self_sent.add(command)

    url = esp32_command_url(command)
    try:
        with urllib.request.urlopen(url, timeout=timeout) as response:
            body = response.read(160).decode("utf-8", errors="ignore")
            ok = 200 <= response.status < 300
            log(f"[RPI -> ESP32] {command} HTTP {response.status} {body[:90]}")
            return ok
    except Exception as exc:
        log(f"[RPI -> ESP32 ERROR] {command}: {exc}")
        return False


def notify_mode_manager(mode: str) -> bool:
    mode = mode.upper().strip()
    url = RPI_MODE_URL + "?mode=" + urllib.parse.quote(mode, safe="")
    try:
        with urllib.request.urlopen(url, timeout=1.5) as response:
            body = response.read(160).decode("utf-8", errors="ignore")
            ok = 200 <= response.status < 300
            log(f"[VOICE -> MAIN] mode={mode} HTTP {response.status} {body[:90]}")
            return ok
    except Exception as exc:
        log(f"[VOICE -> MAIN ERROR] mode={mode}: {exc}")
        return False


# ============================================================
# Audio system
# ============================================================

class IdleMusicPlayer:
    def __init__(self, music_path: Path):
        self.music_path = music_path
        self._process: Optional[subprocess.Popen] = None
        self._lock = threading.Lock()
        self._mpg123 = find_binary(["mpg123"])
        self._ffplay = find_binary(["ffplay"])

    @property
    def is_playing(self) -> bool:
        with self._lock:
            return self._process is not None and self._process.poll() is None

    def start(self) -> None:
        with self._lock:
            if self._process is not None and self._process.poll() is None:
                return

            if not self.music_path.exists():
                return

            suffix = self.music_path.suffix.lower()
            if suffix == ".mp3" and self._mpg123:
                cmd = [self._mpg123, "-q", "--loop", "-1", str(self.music_path)]
            elif self._ffplay:
                cmd = [self._ffplay, "-nodisp", "-loglevel", "quiet", "-loop", "0", str(self.music_path)]
            elif self._mpg123:
                cmd = [self._mpg123, "-q", "--loop", "-1", str(self.music_path)]
            else:
                log("[MUSIC] No player found. Install mpg123 or ffmpeg.")
                return

            try:
                self._process = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                log(f"[MUSIC] Playing idle music: {self.music_path.name}")
            except Exception as exc:
                log(f"[MUSIC ERROR] {exc}")
                self._process = None

    def stop(self) -> None:
        with self._lock:
            proc = self._process
            self._process = None

        if proc is not None and proc.poll() is None:
            try:
                proc.terminate()
                proc.wait(timeout=1.0)
            except Exception:
                try:
                    proc.kill()
                except Exception:
                    pass


class Speaker:
    def __init__(self, music_player: IdleMusicPlayer):
        self.music_player = music_player
        self.tts_bin = find_binary(TTS_BINARIES)
        self._lock = threading.Lock()

    def speak(self, text: str) -> None:
        text = text.strip()
        if not text:
            return

        self.music_player.stop()

        with self._lock:
            log(f"[SPEAK] {text}")
            if not self.tts_bin:
                log("[SPEAK WARN] No TTS found. Install: sudo apt install -y espeak-ng")
                return

            try:
                subprocess.run(
                    [self.tts_bin, "-v", TTS_VOICE, "-s", str(TTS_SPEED), text],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    check=False,
                )
            except Exception as exc:
                log(f"[SPEAK ERROR] {exc}")


# ============================================================
# Command-to-speech
# ============================================================

def command_to_speech(command: str) -> str:
    cmd = command.strip()
    upper = cmd.upper()

    fixed = {
        "FORWARD": "Robot received forward command.",
        "BACKWARD": "Robot received backward command.",
        "LEFT": "Robot received left command.",
        "RIGHT": "Robot received right command.",
        "STOP": "Robot received stop command.",
        "ESTOP": "Emergency stop received.",
        "SYS:MODE:AUTO": "System mode changed to automatic. Starting camera scan and full scenario.",
        "SYS:MODE:MANUAL": "System mode changed to manual. Stopping automatic camera scan.",
        "AUTO:FULL_SCENARIO": "Full automatic scenario command received.",
        "AUTO:UP_STAIRS": "Automatic stair climbing command received.",
        "AUTO:DOWN_STAIRS": "Automatic stair descending command received.",
        "AUTO:STOP": "Automatic mode stop command received.",
        "BLOCK:STOP": "Block stop command received.",
        "ARM:READY": "Robotic arm ready command received.",
        "ARM:HOME": "Robotic arm home command received.",
        "ARM:DROP": "Robotic arm drop command received.",
        "ARM:STOP": "Robotic arm stop command received.",
    }

    if upper in fixed:
        return fixed[upper]

    parts = upper.split(":")

    if len(parts) == 4 and parts[0] == "BLOCK" and parts[1] == "TURN":
        return f"Robot received turn {parts[2].lower()} {parts[3]} degrees."

    if len(parts) == 4 and parts[0] == "BLOCK" and parts[1] == "GO":
        return f"Robot received move {parts[2].lower()} {parts[3]} steps."

    if upper.startswith("SPEED:"):
        return f"Speed command received. Speed {upper.split(':', 1)[1]}."

    if upper.startswith("JACK:") or upper.startswith("BLOCK:JACK:"):
        return f"Jack command received. {upper.replace(':', ' ').lower()}."

    if upper.startswith("CAM:"):
        return f"Camera command received. {upper.replace(':', ' ').lower()}."

    if upper.startswith("ARM:"):
        return f"Arm command received. {upper.replace(':', ' ').lower()}."

    if upper.startswith("AUTO:"):
        return f"Automatic command received. {upper.replace(':', ' ').lower()}."

    if upper.startswith("BLOCK:"):
        return f"Block command received. {upper.replace(':', ' ').lower()}."

    return f"Robot received command {cmd.replace(':', ' ')}."


# ============================================================
# Auto mode camera scanning
# ============================================================

class AutoModeController:
    def __init__(self, speaker: Speaker):
        self.speaker = speaker
        self._auto_active = False
        self._scan_thread: Optional[threading.Thread] = None
        self._lock = threading.RLock()
        self._last_mode = "MANUAL"
        self._last_mode_at = 0.0

    @property
    def auto_active(self) -> bool:
        with self._lock:
            return self._auto_active

    def apply_system_mode(self, mode: str) -> None:
        mode = mode.upper().strip()
        now = time.time()

        with self._lock:
            if mode == self._last_mode and now - self._last_mode_at < SYSTEM_MODE_DUPLICATE_WINDOW_SEC:
                log(f"[MODE] Duplicate {mode} ignored")
                return
            self._last_mode = mode
            self._last_mode_at = now

        if mode == "AUTO":
            self.start_auto_mode()
        elif mode == "MANUAL":
            self.start_manual_mode()

    def start_auto_mode(self) -> None:
        with self._lock:
            if self._auto_active:
                return
            self._auto_active = True

        log("[AUTO MODE] Raspberry AUTO logic active")
        notify_mode_manager("AUTO")

        if AUTO_SCAN_ENABLED:
            self._scan_thread = threading.Thread(target=self._scan_loop, daemon=True)
            self._scan_thread.start()

        if SEND_FULL_SCENARIO_ON_AUTO:
            threading.Thread(target=self._send_full_scenario_delayed, daemon=True).start()

    def start_manual_mode(self) -> None:
        with self._lock:
            was_auto = self._auto_active
            self._auto_active = False

        log("[MANUAL MODE] Raspberry MANUAL logic active")
        notify_mode_manager("MANUAL")

        if was_auto:
            send_command_to_esp32("CAM:STOP")
            time.sleep(0.1)
            # Servo range is 0..90 in ESP32 clean code, so 45 is center.
            send_command_to_esp32("CAM:ANGLE:45")

    def _send_full_scenario_delayed(self) -> None:
        time.sleep(FULL_SCENARIO_DELAY_SEC)
        if not self.auto_active or _stop_event.is_set():
            return

        self.speaker.speak("Starting full automatic scenario.")
        send_command_to_esp32("AUTO:FULL_SCENARIO")

    def _scan_loop(self) -> None:
        log("[AUTO CAMERA SCAN] Started")

        send_command_to_esp32("CAM:SPEED:700")
        send_command_to_esp32("CAM:ANGLE:0")
        time.sleep(AUTO_SCAN_DELAY_SEC)

        while self.auto_active and not _stop_event.is_set():
            # Left scan at low angle.
            send_command_to_esp32("CAM:ANGLE:0")
            time.sleep(0.15)
            send_command_to_esp32(f"CAM:STEP_LEFT:{AUTO_SCAN_STEP_LEFT}")
            time.sleep(AUTO_SCAN_DELAY_SEC)

            if not self.auto_active or _stop_event.is_set():
                break

            # Right scan at middle angle.
            send_command_to_esp32("CAM:ANGLE:45")
            time.sleep(0.15)
            send_command_to_esp32(f"CAM:STEP_RIGHT:{AUTO_SCAN_STEP_RIGHT}")
            time.sleep(AUTO_SCAN_DELAY_SEC)

            if not self.auto_active or _stop_event.is_set():
                break

            # High angle, then return some steps to avoid drifting forever.
            send_command_to_esp32("CAM:ANGLE:90")
            time.sleep(0.15)
            send_command_to_esp32(f"CAM:STEP_LEFT:{AUTO_SCAN_RETURN_LEFT}")
            time.sleep(AUTO_SCAN_CYCLE_PAUSE_SEC)

        send_command_to_esp32("CAM:STOP")
        log("[AUTO CAMERA SCAN] Stopped")


# ============================================================
# UDP command listener
# ============================================================

@dataclass
class MirrorMessage:
    command: str
    direction: str = "UNKNOWN"
    target: str = "UNKNOWN"
    mode: str = "UNKNOWN"
    raw: str = ""


def parse_mirror_message(data: bytes) -> Optional[MirrorMessage]:
    raw = data.decode("utf-8", errors="ignore").strip()
    if not raw:
        return None

    try:
        obj = json.loads(raw)
        command = str(obj.get("command", "")).strip()
        if not command:
            return None
        return MirrorMessage(
            command=command,
            direction=str(obj.get("direction", "UNKNOWN")),
            target=str(obj.get("target", "UNKNOWN")),
            mode=str(obj.get("mode", "UNKNOWN")),
            raw=raw,
        )
    except Exception:
        return MirrorMessage(command=raw, raw=raw)


class CommandListener:
    def __init__(self, speaker: Speaker, auto_controller: AutoModeController, music: IdleMusicPlayer):
        self.speaker = speaker
        self.auto_controller = auto_controller
        self.music = music
        self.last_command = ""
        self.last_command_at = 0.0
        self.last_any_command_at = time.time()
        self._lock = threading.Lock()

    def start(self) -> None:
        threading.Thread(target=self._idle_music_loop, daemon=True).start()
        self._listen_udp()

    def _listen_udp(self) -> None:
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock.bind((UDP_LISTEN_IP, UDP_LISTEN_PORT))
        sock.settimeout(0.5)

        log("========================================")
        log("Apex Rover Raspberry Voice Auto Service")
        log(f"Listening UDP : {UDP_LISTEN_IP}:{UDP_LISTEN_PORT}")
        log(f"ESP32 HTTP    : http://{ESP32_IP}:{ESP32_HTTP_PORT}")
        log(f"Mode manager  : {RPI_MODE_URL}")
        log(f"Idle music    : {IDLE_MUSIC_FILE}")
        log("Mega USB Serial reading on Raspberry: DISABLED")
        log("========================================")

        while not _stop_event.is_set():
            try:
                data, addr = sock.recvfrom(4096)
            except socket.timeout:
                continue
            except Exception as exc:
                log(f"[UDP ERROR] {exc}")
                continue

            msg = parse_mirror_message(data)
            if msg is None:
                continue

            log(f"[UDP FROM {addr[0]}] {msg.direction} {msg.target} {msg.command}")
            self.handle_command(msg)

        sock.close()

    def handle_command(self, msg: MirrorMessage) -> None:
        command = msg.command.strip()
        if not command:
            return

        now = time.time()

        with self._lock:
            self.last_any_command_at = now

            if self_sent.should_ignore(command):
                log(f"[SELF-SENT IGNORED] {command}")
                return

            if command == self.last_command and now - self.last_command_at < DUPLICATE_COMMAND_WINDOW_SEC:
                log(f"[DUPLICATE IGNORED] {command}")
                return

            self.last_command = command
            self.last_command_at = now

        upper = command.upper()

        # Speak every external command received by the robot.
        self.speaker.speak(command_to_speech(command))

        # Only system commands are applied on Raspberry.
        if upper == "SYS:MODE:AUTO":
            self.auto_controller.apply_system_mode("AUTO")
        elif upper == "SYS:MODE:MANUAL":
            self.auto_controller.apply_system_mode("MANUAL")

    def _idle_music_loop(self) -> None:
        while not _stop_event.is_set():
            time.sleep(0.5)
            with self._lock:
                idle_for = time.time() - self.last_any_command_at

            if idle_for >= IDLE_MUSIC_DELAY_SEC:
                self.music.start()


def shutdown(signum=None, frame=None) -> None:
    log("[SYSTEM] Shutting down...")
    _stop_event.set()


def main() -> None:
    signal.signal(signal.SIGINT, shutdown)
    signal.signal(signal.SIGTERM, shutdown)

    music = IdleMusicPlayer(IDLE_MUSIC_FILE)
    speaker = Speaker(music)
    auto_controller = AutoModeController(speaker)
    listener = CommandListener(speaker, auto_controller, music)

    try:
        listener.start()
    finally:
        auto_controller.start_manual_mode()
        music.stop()
        log("[SYSTEM] Stopped")


if __name__ == "__main__":
    main()
